In [1]:
import pandas as pd

In [2]:
file_name = './data/expand_mini.xlsx'
df = pd.read_excel(file_name) # padas
data = df
data

,측정날짜,측정소명,수온,수소이온농도,전기전도도,용존산소,탁도,총유기탄소,총질소,총인,클로로필-a,미생물_독성지수
0,2019.01.01 00:00,가평,2.8,6.8,97.0,12.6,0.5,1.4,1.771,0.004,3.8,4.5
1,2019.01.01 01:00,가평,2.8,6.8,97.0,12.6,0.6,1.4,1.812,0.005,4.1,2.5
2,2019.01.01 02:00,가평,NaN,NaN,NaN,12.6,0.4,1.4,1.765,0.003,3.8,1.0
3,2019.01.01 03:00,가평,2.7,6.8,97.0,12.6,0.5,1.4,1.775,0.005,3.9,1.0
4,2019.01.01 04:00,가평,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,2019.01.01 05:00,가평,NaN,21.0,41.0,12.5,0.4,1.4,1.805,0.002,3.7,2.5
6,2019.01.01 06:00,가평,2.0,22.0,42.0,12.5,0.5,1.4,1.793,0.003,3.8,0.9
7,2019.01.01 07:00,가평,3.0,NaN,43.0,12.5,0.4,1.4,1.752,0.002,3.8,-1.2
8,2019.01.01 08:00,가평,NaN,NaN,NaN,12.5,0.4,1.4,1.789,0.002,3.7,-0.3
9,2019.01.01 09:00,가평,4.0,NaN,44.0,12.6,0.4,1.4,1.792,0.001,3.4,-0.4
10,2019.01.01 10:00,가평,5.0,25.0,45.0,12.7,0.5,1.4,1.794,0.003,3.3,-0.5
11,2019.01.01 11:00,가평,6.0,26.0,NaN,12.7,0.4,1.4,1.823,0.003,2.4,-0.2
12,2019.01.01 12:00,가평,7.0,27.0,NaN,12.7,0.4,1.4,1.829,0.005,1.9,0.2
13,2019.01.01 13:00,가평,8.0,NaN,NaN,12.5,0.4,1.4,1.793,0.004,2.3,-2.6
14,2019.01.01 14:00,가평,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,2019.01.01 15:00,가평,9.0,NaN,49.0,12.5,0.4,1.4,1.764,0.003,2.6,-0.2
16,2019.01.01 16:00,가평,10.0,NaN,50.0,12.5,0.5,1.4,1.782,0.002,3.8,-1.0
17,2019.01.01 17:00,가평,NaN,NaN,51.0,12.6,0.5,1.4,1.765,0.004,4.0,-0.3
18,2019.01.01 18:00,가평,NaN,32.0,52.0,NaN,0.4,1.4,1.761,0.005,4.0,1.7
19,2019.01.01 19:00,가평,13.0,33.0,53.0,NaN,0.5,NaN,1.749,0.003,4.1,1.6

In [3]:
fill_cnt = 2
mask = data.copy()
for i in data.columns: 
    df = pd.DataFrame( data[i] )
    df['new'] = ((df.notnull() != df.shift().notnull()).cumsum())
    df['ones'] = 1
    mask[i] = (df.groupby('new')['ones'].transform('count') < fill_cnt+1) | data[i].notnull()
mask

,측정날짜,측정소명,수온,수소이온농도,전기전도도,용존산소,탁도,총유기탄소,총질소,총인,클로로필-a,미생물_독성지수
0,True,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,True,True
5,True,True,True,True,True,True,True,True,True,True,True,True
6,True,True,True,True,True,True,True,True,True,True,True,True
7,True,True,True,False,True,True,True,True,True,True,True,True
8,True,True,True,False,True,True,True,True,True,True,True,True
9,True,True,True,False,True,True,True,True,True,True,True,True
10,True,True,True,True,True,True,True,True,True,True,True,True
11,True,True,True,True,False,True,True,True,True,True,True,True
12,True,True,True,True,False,True,True,True,True,True,True,True
13,True,True,True,False,False,True,True,True,True,True,True,True
14,True,True,True,False,False,True,True,True,True,True,True,True
15,True,True,True,False,True,True,True,True,True,True,True,True
16,True,True,True,False,True,True,True,True,True,True,True,True
17,True,True,True,False,True,True,True,True,True,True,True,True
18,True,True,True,True,True,True,True,True,True,True,True,True
19,True,True,True,True,True,True,True,True,True,True,True,True

In [4]:
data.interpolate().bfill()[mask]

,측정날짜,측정소명,수온,수소이온농도,전기전도도,용존산소,탁도,총유기탄소,총질소,총인,클로로필-a,미생물_독성지수
0,2019.01.01 00:00,가평,2.800000,6.8,97.0,12.60,0.50,1.4,1.7710,0.0040,3.80,4.50
1,2019.01.01 01:00,가평,2.800000,6.8,97.0,12.60,0.60,1.4,1.8120,0.0050,4.10,2.50
2,2019.01.01 02:00,가평,2.750000,6.8,97.0,12.60,0.40,1.4,1.7650,0.0030,3.80,1.00
3,2019.01.01 03:00,가평,2.700000,6.8,97.0,12.60,0.50,1.4,1.7750,0.0050,3.90,1.00
4,2019.01.01 04:00,가평,2.466667,13.9,69.0,12.55,0.45,1.4,1.7900,0.0035,3.80,1.75
5,2019.01.01 05:00,가평,2.233333,21.0,41.0,12.50,0.40,1.4,1.8050,0.0020,3.70,2.50
6,2019.01.01 06:00,가평,2.000000,22.0,42.0,12.50,0.50,1.4,1.7930,0.0030,3.80,0.90
7,2019.01.01 07:00,가평,3.000000,NaN,43.0,12.50,0.40,1.4,1.7520,0.0020,3.80,-1.20
8,2019.01.01 08:00,가평,3.500000,NaN,43.5,12.50,0.40,1.4,1.7890,0.0020,3.70,-0.30
9,2019.01.01 09:00,가평,4.000000,NaN,44.0,12.60,0.40,1.4,1.7920,0.0010,3.40,-0.40
10,2019.01.01 10:00,가평,5.000000,25.0,45.0,12.70,0.50,1.4,1.7940,0.0030,3.30,-0.50
11,2019.01.01 11:00,가평,6.000000,26.0,NaN,12.70,0.40,1.4,1.8230,0.0030,2.40,-0.20
12,2019.01.01 12:00,가평,7.000000,27.0,NaN,12.70,0.40,1.4,1.8290,0.0050,1.90,0.20
13,2019.01.01 13:00,가평,8.000000,NaN,NaN,12.50,0.40,1.4,1.7930,0.0040,2.30,-2.60
14,2019.01.01 14:00,가평,8.500000,NaN,NaN,12.50,0.40,1.4,1.7785,0.0035,2.45,-1.40
15,2019.01.01 15:00,가평,9.000000,NaN,49.0,12.50,0.40,1.4,1.7640,0.0030,2.60,-0.20
16,2019.01.01 16:00,가평,10.000000,NaN,50.0,12.50,0.50,1.4,1.7820,0.0020,3.80,-1.00
17,2019.01.01 17:00,가평,11.000000,NaN,51.0,12.60,0.50,1.4,1.7650,0.0040,4.00,-0.30
18,2019.01.01 18:00,가평,12.000000,32.0,52.0,12.60,0.40,1.4,1.7610,0.0050,4.00,1.70
19,2019.01.01 19:00,가평,13.000000,33.0,53.0,12.60,0.50,1.4,1.7490,0.0030,4.10,1.60